language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  - SYMFONY_VERSION=2.6.*

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.5.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
  allow_failures:
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist
  - vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh

script: phpunit --coverage-text

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
